# Generated by Django 5.2.5 on 2025-09-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.jpg', upload_to='avatar/'),
        ),
    ]
