# Generated by Django 5.2.5 on 2025-09-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profiles_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.jpg', upload_to='avatars/'),
        ),
    ]
